wandb_version: 1

epochs:
  desc: null
  value: 15
lr:
  desc: null
  value: 0.0001
batch_size:
  desc: null
  value: 32
optimizer:
  desc: null
  value: Adam
model:
  desc: null
  value: "animal_model(\n  (features): Sequential(\n    (0): Conv2d(3, 32, kernel_size=(3,\
    \ 3), stride=(1, 1), padding=(1, 1))\n    (1): ReLU()\n    (2): MaxPool2d(kernel_size=2,\
    \ stride=2, padding=0, dilation=1, ceil_mode=False)\n    (3): Conv2d(32, 64, kernel_size=(3,\
    \ 3), stride=(1, 1), padding=(1, 1))\n    (4): ReLU()\n    (5): MaxPool2d(kernel_size=2,\
    \ stride=2, padding=0, dilation=1, ceil_mode=False)\n    (6): Conv2d(64, 128,\
    \ kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))\n    (7): ReLU()\n    (8):\
    \ MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)\n\
    \    (9): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))\n\
    \    (10): ReLU()\n    (11): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1,\
    \ ceil_mode=False)\n  )\n  (classifier): Sequential(\n    (0): Flatten(start_dim=1,\
    \ end_dim=-1)\n    (1): Linear(in_features=50176, out_features=512, bias=True)\n\
    \    (2): ReLU()\n    (3): Dropout(p=0.5, inplace=False)\n    (4): Linear(in_features=512,\
    \ out_features=10, bias=True)\n  )\n)"
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1764355403.6582
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.12
      5: 0.16.3
      8:
      - 1
      - 5
      13: linux-x86_64
